name: Selenium Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Install Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 131
        install-chromedriver: true

    - name: Install Dependencies with Bundler
      run: |
        gem install bundler
        bundle install

    - name: Run Scraper
      run: bundle exec ruby scraper.rb

    - name: Commit and Push CSV File to Repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add fiis.csv
        git add acoes.csv
        git commit -m "Add scraped data"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}